theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: BlueSam's blog
description: Personal site of BlueSam1905 aka Atike Sami. This site has all my works like CTF writeups, Projects, research works, etc
