baseURL: # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: BlueSam1905
paginate: 5
theme: charlolamode



menu:
    main:
        - name: Articles
          url: /articles/
          weight: 20
        - name: Projects
          url: /projects/
          weight: 15
        - name: Writeups
          url: /writeups/
          weight: 10
     # - name: Categories
        #   url: /categories/
        #   weight: 10
        # - name: new Tab
        #   url: /newtab/
        #   weight: defines order of tabs
   


params:
    author: Author's Name


    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        title: BlueSam1905
        description: |
          You can find my CTF writeups, Projects, Research works, Blogs etc here. 

        imageUrl: "images/profile-pic.jpg"
        imageTitle: my image
        imageWidth: 120
        imageHeight: 120
        buttons:
            - name: Don't click me
              url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
    mainSections:
      - articles

    socialIcons:
        - name: facebook
          url: "https://www.facebook.com/atik.sami.7"
        - name: github
          url: "https://github.com/BlueSam1905"
        - name: instagram
          url: "https://www.instagram.com/samzowisky/"



    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ic"
          favicon16x16: "/images/favicon-16x16.pn"
          favicon32x32: "/images/favicon-32x32.pn"
          apple_touch_icon: "/images/apple-touch-icon.pn"
          safari_pinned_tab: "/images/apple-touch-icon.pn"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true